### ISSUE TITLE
Not able to select preferences in an application if the option name is long

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3395] opened 2023-04-12 20:38 UTC
The normal data structure if you try and save a preference that collects an address is that both fields come through where the first is the checkbox and the second is the address data where the address field name has an `-address` suffix on the same key, for example `AddressQuestion: true` and `AddressQuestion-address: { ...address } `

For some reason when the option name is very long this data structure comes through instead `VeryLongQuestionName: { -address: { ...address } }` and since this doesn't conform to what we expect the `mapCheckboxesToApi` function is not adding this information to the draft application data. The result is that you cannot claim a preference that selects an address if the option name is long (unclear how long).

At the same time we have differently structured preferences with long names + address collection working in production, so it could be some combination of the fact that it is multiselect or that the user can opt out. At the very least option length is related because if I reduce the length of the option title it works.

**Comment by emilyjablonski** [comment] 2023-04-12 21:24
![Uploading Screenshot 2023-04-12 at 3.24.32 PM.png…]()

**Comment by ludtkemorgan** [comment] 2023-04-24 22:40
@emilyjablonski I was unable to reproduce this locally. When applying to a property with a long preference it saved correctly and returned the preference selected in the response.
![image](https://user-images.githubusercontent.com/42942267/234124864-033e6956-3150-44c3-9bfe-19cc5a064cea.png)

I also did it with a property in the dev site for the preference you reference in your example and it saved correctly.

I'll keep trying different variables, but let me know if you are able to reproduce it

**Comment by sarahlazarich** [comment] 2023-05-11 14:39
unable to repro, moving to icebox.

**Comment by YazeedLoonat** [comment] 2023-05-31 21:45
Hey @emilyjablonski could you try to repro again or create an example we could see on a stood up env

**Comment by emilyjablonski** [comment] 2023-05-31 21:47
@YazeedLoonat I wasn't able to repro

**Comment by YazeedLoonat** [comment] 2023-05-31 22:05
roger closing this one out then

**Closed by YazeedLoonat** 2023-05-31 22:05 UTC
Labels: could not repro
