### ISSUE TITLE
AC: Incorrect duplicate display in Partners

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/bloom#3517] opened 2023-06-20 18:49 UTC
Depot Apartments has 1 applicant (Brisaida Valencia) showing 4,367 pending review applications and the system locks up when they try to resolve. We have not seen this occur on any other listings, but we were able to replicate the issue on Depot. The main listings view and listing export are behaving normally. This is a low priority issue.

 ![Screenshot 2023-06-20 at 2.45.29 PM.png](https://images.zenhubusercontent.com/628807cfd47647a5b2738c30/7e4b274a-6fda-4d55-8abb-bc1a09c0b360)

**Comment by ludtkemorgan** [comment] 2023-06-21 21:07
Initial findings: Since the release on 06/15 the afs cron job is comparing all applicants that don't have an email together. In other words it thinks there is a duplicate group of "Email" if more than one applicant doesn't have an email. 

We will need to have two fixes, the first one is to prevent this from happening in the future. The second step is deleting these "null" afs values and reset the last run timestamp for the impacted listings to an earlier time.

**Comment by ludtkemorgan** [comment] 2023-06-28 16:20
This change has been released and fixed for the Depot Community Apartment. I will also fix the other 8 listings that have been impacted, but no new listings should be impacted by this issue

**Comment by sarahlazarich** [comment] 2023-07-12 20:47
@ludtkemorgan are we good to close this?

**Comment by ludtkemorgan** [comment] 2023-07-17 23:27
@sarahlazarich This has been verified that the issue is no longer happening. I still need to clean up the remaining 7 properties and will close this ticket when that is completed

**Comment by ludtkemorgan** [comment] 2023-07-18 14:18
The 7 remaining properties have been cleaned up. I will close this ticket as complete

**Closed by ludtkemorgan** 2023-07-18 14:18 UTC
