### ISSUE TITLE
Bug: Incorrect Alert Box Error on Forgot Password

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3181] opened 2022-11-22 18:03 UTC
<img width="556" alt="Screen Shot 2022-11-22 at 9 44 34 AM" src="https://user-images.githubusercontent.com/53269332/203388291-6400d677-db61-4294-8668-5707361dd585.png">

It should also be checked that there are no other instances of this issue in Partners

**Comment by ludtkemorgan** [comment] 2022-11-23 15:59
Closing this as it is a duplicate of #2346. Adding this screenshot to that issue for better context

**Closed by ludtkemorgan** 2022-11-23 15:59 UTC
Labels: bug
