### ISSUE TITLE
Uploading lottery results to a listing causes inability to save changes

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4216] opened 2024-07-22 22:43 UTC
After you upload lottery results to a closed listing, further edits to the listing fail.

**Comment by sarahlazarich** [comment] 2024-08-14 16:18
Dupe of https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4242

**Closed by sarahlazarich** 2024-08-14 16:18 UTC
