### ISSUE TITLE
UI Components - Pull into its own repo

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#2951] opened 2022-08-11 20:01 UTC
Through a lot of discussion and consideration, we have decided to pull UI Components out of the main repo and have it as its own standalone repository. In this iteration, we will do just that, but leave UI Components in the mono repo for in case we run into any issues.

Create a new repo under [bloom-housing](https://github.com/bloom-housing). I'm not sure if we have decided on a name for it, and if not, then call it ui-components.

There will be follow-up issues to address publishing, dependencies and linking for local development.

**Comment by ludtkemorgan** [comment] 2022-11-23 15:53
This is a duplicate of #3148 so closing issue

**Closed by ludtkemorgan** 2022-11-23 15:53 UTC
