### ISSUE TITLE
Income step blocking application submission

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#3497] opened 2023-06-05 22:27 UTC
Some applicants are not able to move past the income step for the Berkeley Place listing.

We don't have more context yet from applicants about what error they are seeing or what they are entering.

**Comment by sarahlazarich** [comment] 2023-06-14 16:31
Per [slack thread](https://exygy.slack.com/archives/C02G1S19QA2/p1686760201004149?thread_ts=1685452579.403149&cid=C02G1S19QA2), can't repro, moving to backlog.

**Comment by ColinBuyck** [comment] 2023-09-20 21:53
Duplicate of #3487

**Closed by ColinBuyck** 2023-09-20 21:53 UTC
