### ISSUE TITLE
Allow LinkButton to take an internal link

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#2325] opened 2021-12-17 20:15 UTC
LinkButton should be able to be passed an internal link (ie `#section` to jump further down the page)

**Comment by seanmalbert** [comment] 2022-02-03 23:20
This will come in handy for displaying field validations at the top of a form.

**Comment by seanmalbert** [comment] 2022-02-03 23:20
This is a duplicate of #2324

**Closed by seanmalbert** 2022-02-03 23:20 UTC
