### ISSUE TITLE
Bug - Listing add/edit form throws console errors on local

### ISSUE THREAD

**Issue by ludtkemorgan** [bloom-housing/bloom#3392] opened 2023-04-12 17:07 UTC
The add/edit listing form in partners is outputting a lot of console log errors from the Textarea component
![image](https://user-images.githubusercontent.com/42942267/231530810-9077b733-1961-426a-8390-6218b6da9e33.png)

This might be an issue with either how we are using the Textarea component on the partner site or potentially the ui-component component 

**To Reproduce**
1. Go to Partners site locally
2. Click on "add listing"
4. See error in the console

**Comment by sarahlazarich** [comment] 2023-05-03 22:23
closing, duplicate of https://github.com/bloom-housing/ui-components/issues/104

**Closed by sarahlazarich** 2023-05-03 22:23 UTC
Labels: bug
